[package]
name = "flexi_logger"
version = "0.12.0"
authors = ["emabee <meinolf.block@sap.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/emabee/flexi_logger"
documentation = "https://docs.rs/flexi_logger"
homepage = "https://crates.io/crates/flexi_logger"
description = """
An easy-to-configure and flexible logger that writes logs to stderr and/or to files. \
It allows custom logline formats, and it allows changing the log specification at runtime. \
It also allows defining additional log streams, e.g. for alert or security messages.\
"""
keywords = ["file", "logger"]
categories = ["development-tools::debugging"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["colors"]
colors = ["yansi"]
specfile = ["serde","toml","notify", "serde_derive"]
syslog_writer = ["libc", "hostname"]
ziplogs = ["zip"]

[dependencies]
chrono = "0.4"
glob = "0.3"
hostname = {version = "0.1", optional = true}
log = { version = "0.4", features = ["std"] }
notify = { version = "4.0", optional = true }
regex = "1.1"
serde = { version = "1.0", optional = true }
serde_derive = {version = "1.0", optional = true}
toml = { version = "0.5", optional = true }
yansi = {version = "0.5", optional = true}
zip = {version = "0.5", optional = true}

[target.'cfg(linux)'.dependencies]
libc = {version = "^0.2.50", optional = true}

[dev-dependencies]
serde_derive = "1.0"
version-sync = "0.8"
